-- Deshabilitar RLS temporalmente para pruebas
ALTER TABLE cobradores DISABLE ROW LEVEL SECURITY;
ALTER TABLE apk_builds DISABLE ROW LEVEL SECURITY;
ALTER TABLE build_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE build_metrics DISABLE ROW LEVEL SECURITY;